name: emtro
favicon: null
layout_spectrum: 0.9212325478438288
typography_spectrum: 0.4703347967006266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4444665589835495
  lightness: 0.7123148548416793
  saturation: 0.17900322657078505
  rhythmicContrast: 0.08122593956068158
purpose: []
